apiVersion: v1
kind: Namespace
metadata:
  name: ahava-ml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ahava-ml-service
  namespace: ahava-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ahava-ml-service
  template:
    metadata:
      labels:
        app: ahava-ml-service
    spec:
      containers:
        - name: ml-service
          image: mphobeethwala/ahava-mlservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: ahava-ml-service
  namespace: ahava-ml
spec:
  selector:
    app: ahava-ml-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
